name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ng build --prod --base-href ./

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: main
          folder: ./docs
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
